# Generated by Django 4.1.3 on 2022-11-19 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paystackpay', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Order_notes',
            new_name='order_notes',
        ),
    ]
