# Generated by Django 4.1.3 on 2022-11-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paystackpay', '0002_rename_order_notes_payment_order_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order_notes',
            new_name='order_note',
        ),
    ]
