# Generated by Django 4.1.3 on 2022-11-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystackpay', '0003_rename_order_notes_payment_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ref',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
