# Generated by Django 4.1.3 on 2022-12-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystackpay', '0005_payment_date_expected'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
