# Generated by Django 4.1.3 on 2022-12-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystackpay', '0006_payment_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ref',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
    ]
