# Generated by Django 4.1.3 on 2022-12-29 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_customeraddress_phone'),
        ('paystackpay', '0007_alter_payment_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cartorder'),
        ),
    ]
