# Generated by Django 4.1.3 on 2022-11-15 15:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100, null=True)),
                ('ingredients', models.CharField(blank=True, max_length=300, null=True)),
                ('package', models.CharField(max_length=300, null=True)),
                ('item_number', models.IntegerField(blank=True, null=True)),
                ('prod_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Product Info',
            },
        ),
    ]
