# Generated by Django 4.1.3 on 2022-11-15 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productinformation_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinformation',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productinformation',
            name='prod_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
