# Generated by Django 4.1.3 on 2022-11-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_review_rating_review_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='topic_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('1', '1 Star'), ('2', '2 Stars'), ('3', '3 Stars'), ('4', '4 Stars'), ('5', '5 Stars')], max_length=150),
        ),
    ]
