# Generated by Django 4.1.3 on 2022-11-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_topic_views_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='dis_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
