# Generated by Django 4.1.3 on 2022-11-16 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_variation_dis_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='dis_price',
        ),
    ]
