# Generated by Django 4.1.3 on 2022-11-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_variation_dis_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='dis_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
