# Generated by Django 4.1.3 on 2022-12-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_productimage_options_remove_product_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
