# Generated by Django 4.1.3 on 2022-12-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinformation',
            name='item_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='productinformation',
            name='package',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
