# Generated by Django 4.1.3 on 2022-12-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_productinformation_item_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumb_nail',
            field=models.ImageField(null=True, upload_to='product_img/'),
        ),
    ]
