# Generated by Django 4.1.3 on 2022-12-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_product_thumb_nail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='number',
        ),
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
