# Generated by Django 4.1.3 on 2022-12-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
