# Generated by Django 4.1.3 on 2023-03-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
