# Generated by Django 4.1.3 on 2023-03-30 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_product_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinformation',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productinformation',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productinformation',
            name='prod_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='variation',
            name='dis_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
