# Generated by Django 4.1.3 on 2022-12-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelcartReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('star', models.CharField(choices=[('1', '1 Star'), ('2', '2 Stars'), ('3', '3 Stars'), ('4', '4 Stars'), ('5', '5 Stars')], max_length=150)),
            ],
        ),
    ]
