# Generated by Django 4.1.3 on 2023-02-19 05:30

from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_usertoken_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='svg',
            field=models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='svg'),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.state')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
    ]
