# Generated by Django 4.1.3 on 2023-04-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_city_sate_city_price_city_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='svg',
            field=models.FileField(blank=True, null=True, upload_to='svg'),
        ),
    ]
