# Generated by Django 4.1.3 on 2023-04-12 15:46

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_subcategory_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='svg',
            field=models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='svg'),
        ),
    ]
