# Generated by Django 4.1.3 on 2022-11-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_customeraddress_cartorder_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'verbose_name_plural': 'address'},
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='address',
        ),
    ]
