# Generated by Django 4.1.3 on 2022-11-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_customeraddress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
