# Generated by Django 4.1.3 on 2022-12-09 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_customeraddress_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponcode',
            old_name='price',
            new_name='per_off',
        ),
    ]
