# Generated by Django 4.1.3 on 2022-12-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_cartorder_code_alter_cartorder_order_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='vendor',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
