# Generated by Django 4.1.3 on 2022-12-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_cartorderitems_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
