# Generated by Django 4.1.3 on 2022-12-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_customeraddress_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='ref',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
