# Generated by Django 4.1.3 on 2022-12-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_cartorderitems_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='image',
            field=models.ImageField(null=True, upload_to='order/'),
        ),
    ]
