# Generated by Django 4.1.3 on 2023-01-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_alter_cartorderitems_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='delivery',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
