# Generated by Django 4.1.3 on 2023-02-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_cartorder_delivery_cartorder_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
